config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :empresas do 
  	resources :reclamos, only: [:create, :destroy, :update, :edit]
  end

  devise_for :users

  root 'empresas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	has_many :reclamos, dependent: :destroy
end

app/models/reclamo.rb
class Reclamo < ApplicationRecord
  belongs_to :user
  belongs_to :empresa
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reclamos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
    @empresa = Empresa.new
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    @reclamos = Reclamo.all.order('created_at DESC')
  end

  # GET /empresas/new
  def new
    
  end

  # GET /empresas/1/edit
  def edit

  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.create(empresa_params)

    respond_to do |format|
        format.js
    end 
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    @empresa.update(empresa_params)

    respond_to do |format|
        format.js
    end 
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
        format.js
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:name, :description)
    end
end

app/controllers/reclamos_controller.rb
class ReclamosController < ApplicationController
	def create
		@empresa = Empresa.find(params[:empresa_id])
		@reclamo = Reclamo.new(contenido:params[:reclamo][:contenido], user: current_user)
		@reclamo.empresa = @empresa
		@reclamo.save
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/reclamos_helper.rb
module ReclamosHelper
end

app/views/empresas/_form.html.erb
<%= form_with(model: @empresa) do |form| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :empresa_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :empresa_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/empresas/_list.html.erb
<tr>
	<td><%= @empresa.name %></td>
	<td><%= @empresa.description %></td>
	<td><%= link_to 'Show', @empresa %></td>
	<td><%= link_to 'Edit', edit_empresa_path(@empresa), data:{remote:true} %></td>
	<td><%= link_to 'Destroy', @empresa, method: :delete, data: { confirm: 'Are you sure?', remote: true } %></td>
</tr>

app/views/empresas/create.js.erb
$('#empresa').append("<%= j render 'list' %>");

app/views/empresas/destroy.js.erb
$('#<%= @empresa.id %>').toggle(300);

app/views/empresas/edit.html.erb
<h1>Editing Empresa</h1>

<%= render 'form', empresa: @empresa %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/edit.js.erb
$('#empresa_edit').html("<%= j render 'form' %>");
$('#exampleModal').modal('show');

app/views/empresas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empresas</h1>
<div class="row">
  <div class="col-md-6">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody id="empresa">
        <% @empresas.each do |empresa| %>
          <tr id="<%= empresa.id %>">
            <td id="nombre<%= empresa.id %>"><%= empresa.name %></td>
            <td><%= link_to 'Show', empresa %></td>
            <td><%= link_to 'Edit', edit_empresa_path(empresa), data:{remote:true} %></td>
            <td><%= link_to 'Destroy', empresa, method: :delete, data: { confirm: 'Are you sure?', remote:true  } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-6">
    <h2>Crear Empresa</h2>
    <%= form_with(model: @empresa) do |form| %>
      <% if @empresa.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

          <ul>
          <% @empresa.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :empresa_name %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_field :description, id: :empresa_description %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>

  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Editar Comentario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="empresa_edit">
      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/empresas/new.html.erb
<h1>New Empresa</h1>

<%= render 'form', empresa: @empresa %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @empresa.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @empresa.description %>
</p>


<div class="row">
	<div class="col-md-4">
		<div class="well well-sm">
			<legend>Comentar:</legend>
			<%= form_with(model: [@empresa, Reclamo.new], html: { class: 'form-horizontal' }) do |f| %>
				<div class="form-group">
					<div class="col-md-12">
						<%= f.text_area :contenido, placeholder: 'Escribe tu comentario aquí...', class: 'form-control', id: :texto %>
					</div>
				</div>
				<%= f.submit 'Comentar', class: 'btn btn-primary' %>
			<% end %>
			  
		</div>
	</div>

	<div class="col-md-8" id="reclamos">
		<% @reclamos.each do |comentario| %>
			<% if (@empresa.id == comentario.empresa_id) %>
				<div class="well well-sm" id="<%= comentario.id %>">
					<strong><%= comentario.user.email %>:</strong>
					<p><%=comentario.created_at.strftime("%d-%m-%Y--%H:%M:%S")%></p>
					<div id="contenido<%= comentario.id %>">
						<%= comentario.contenido %>
						<br><br>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
</div>



<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/update.js.erb
$('#nombre<%= @empresa.id %>').text("<%= @empresa.name %>");
$('#descripcion<%= @empresa.id %>').text("<%= @empresa.description %>");
$('#exampleModal').modal('hide');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaAjax</title>
    <%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script
	  src="https://code.jquery.com/jquery-3.3.1.min.js"
	  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	  crossorigin="anonymous">
	</script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'shared/navbar' %>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

	
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reclamos/_reclamo.html.erb
<div class="well well-sm" id="<%= @reclamo.id %>">
	<strong><%= @reclamo.user.email %>:</strong>
	<p><%= @reclamo.created_at.strftime("%d-%m-%Y--%H:%M:%S") %></p>
	<%= @reclamo.contenido %>
	<br><br>
</div>

app/views/reclamos/create.js.erb
$('#reclamos').append("<%= j render 'reclamo' %>");
$('#texto').val('');

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="<%= root_path %>">Prueba Ajax</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="<%= root_path %>">Home<span class="sr-only">(current)</span></a>
        <% if user_signed_in? %>
          <a class="nav-item nav-link" href="#">Usuario: <%= current_user.email %></a>
          <%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <% else %>
          <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
          <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
        <% end %>
      </div>
    </div>
  </nav>